- hosts: all
  tasks:
    - name: Get node's system information
      ansible.builtin.setup:
        filter:
          - 'ansible_system'
          - 'ansible_distribution'
          - 'ansible_distribution_*'
          - 'ansible_userspace_architecture'
          - 'ansible_userspace_bits'
          - 'ansible_lsb'
          - 'ansible_os_family'
          - 'ansible_pkg_mgr'
          - 'ansible_service_mgr'
          - 'ansible_architecture'
          - 'ansible_apparmor'
          - 'ansible_is_chroot'
          - 'ansible_selinux'
          - 'ansible_kernel'
          - 'ansible_kernel_version'
          - 'ansible_machine'
          - 'ansible_machine_id'
          - 'ansible_memfree_mb'
          - 'ansible_memtotal_mb'
          - 'ansible_processor'
          - 'ansible_processor_*'
          - 'ansible_uptime_seconds'
          - 'ansible_user_*'
          - 'ansible_effective_group_id'
          - 'ansible_effective_user_id'
          - 'ansible_real_group_id'
          - 'ansible_real_user_id'
          - 'ansible_env'
          - 'ansible_python'
          - 'ansible_nodename'
          - 'ansible_domain'
          - 'ansible_fqdn'
          - 'ansible_hostname'
          - 'ansible_hostnqn'
          - 'ansible_bios_*'
          - 'ansible_board_*'
          - 'ansible_chassis_*'
          - 'ansible_system_*'
          - 'ansible_virtualization_*'
          - 'ansible_form_factor'
          - 'ansible_product_*'
          - 'ansible_cmdline'
          - 'ansible_proc_cmdline'
          - 'ansible_date_time'
      register: sysinfo
    - debug: var=sysinfo
