on:
  release:
    types:
      - published

jobs:
  publish-collection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible
      - name: Build collection
        run: ansible-galaxy collection build
      - name: Publish collection
        run: |
          echo "token: ${{ secrets.ANSIBLE-GALAXY_TOKEN }}" > ~/.ansible/galaxy_token
          ansible-galaxy collection publish $(ls -t *.tar.gz | head -1)
