---
- include_vars:
    file: default.yml

- include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | int }}.yml'
    - '{{ ansible_distribution | lower }}.yml'
    - '{{ ansible_os_family | lower }}.yml'
